# Generated by Django 5.2.12 on 2026-03-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_actionlog_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('courier', 'Kuryer'), ('worker', 'Ishchi'), ('water_filler', "Suv to'ldiruvchi"), ('order_taker', 'Buyurtma qabul qiluvchi')], max_length=30),
        ),
    ]
