# Generated by Django 5.2.12 on 2026-03-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_telegram_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('new', 'Yangi'), ('delivered', 'Yetkazildi'), ('closed', 'Yopiq')], default='new', max_length=20, verbose_name='Yetkazish holati'),
        ),
    ]
