# Generated by Django 5.2.14 on 2026-05-14 04:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_order_delivery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Регион номи')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионлар',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-order_date', '-id'), 'verbose_name': 'Буюртма', 'verbose_name_plural': 'Буюртмаlar'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Буюртма elementi', 'verbose_name_plural': 'Буюртма elementlari'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Маҳсулот', 'verbose_name_plural': 'Маҳсулотlar'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ('name',), 'verbose_name': 'Дўкон', 'verbose_name_plural': 'Дўконlar'},
        ),
        migrations.AlterModelOptions(
            name='shopdeposit',
            options={'ordering': ('-date', '-id'), 'verbose_name': 'Depozit', 'verbose_name_plural': 'Депозитлар'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Фойдаланувчи профили', 'verbose_name_plural': 'Фойдаланувчи профиллари'},
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('created', 'Яратди'), ('updated', 'Таҳрирлади'), ('deleted', 'Ўчирди'), ('shop_created', 'Дўкон қўшилди'), ('order_created', 'Буюртма yaratildi'), ('order_delivered', 'Буюртма yetkazildi')], max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('courier', 'Курер'), ('worker', 'Ишчи'), ('water_filler', 'Сув тўлдирувчи'), ('order_taker', 'Буюртма qabul qiluvchi')], max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('new', 'Янги'), ('delivered', 'Етказилди'), ('closed', 'Ёпиқ')], default='new', max_length=20, verbose_name='Етказиш ҳолати'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, verbose_name='Изоҳ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Сана'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('pickup', 'Заводдан олиб кетиш'), ('delivery', 'Етказиб бериш')], default='pickup', max_length=20, verbose_name='Буюртма тури'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Тўланган сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.shop', verbose_name='Дўкон'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_sale',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Нархи (сўм)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Маҳсулот'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сони'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Маҳсулот nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Нархи (сўм)'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Манзил'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='google_map_link',
            field=models.URLField(blank=True, verbose_name='Google харита ҳаволаси'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='map_link',
            field=models.URLField(blank=True, verbose_name='Локация линқи (эски)'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=160, unique=True, verbose_name='Дўкон номи'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='note',
            field=models.TextField(blank=True, verbose_name='Изоҳ'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone_primary',
            field=models.CharField(blank=True, max_length=25, verbose_name='Телефон 1'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=25, verbose_name='Телефон 2'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='shops/photos/', verbose_name='Дўкон расми'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='yandex_map_link',
            field=models.URLField(blank=True, verbose_name='Yandex харита ҳаволаси'),
        ),
        migrations.AlterField(
            model_name='shopdeposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Миқдор'),
        ),
        migrations.AlterField(
            model_name='shopdeposit',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Сана'),
        ),
        migrations.AlterField(
            model_name='shopdeposit',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Изоҳ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='users/photos/', verbose_name='Профил расми'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_connected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Telegram уланган вақт'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Telegram телефони'),
        ),
        migrations.AddField(
            model_name='shop',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='core.region', verbose_name='Регион'),
        ),
    ]
