from django.urls import path

from core.views import (
    ActivityLogListView,
    ActivityLogDetailJsonView,
    AnalyticsDataView,
    AnalyticsExportExcelView,
    AnalyticsExportPDFView,
    AnalyticsView,
    DashboardView,
    DeliveryDetailView,
    DeliveryListView,
    EmployeeCreateView,
    EmployeeDetailExportExcelView,
    EmployeeDetailExportPDFView,
    EmployeeDetailView,
    EmployeeUpdateView,
    EmployeeListExportExcelView,
    EmployeeListExportPDFView,
    EmployeeListView,
    LoginPageView,
    OrderCreateView,
    OrderDeleteView,
    OrderDetailJsonView,
    OrderExportExcelView,
    OrderExportPDFView,
    OrderListExportExcelView,
    OrderListExportPDFView,
    OrderListView,
    OrderUpdateView,
    ProductCreateView,
    ProductDeleteView,
    ProductListView,
    ProductUpdateView,
    ProfileView,
    ShopCreateView,
    ShopDeleteView,
    ShopDepositCreateView,
    ShopDepositDeleteView,
    ShopDepositUpdateView,
    ShopDetailView,
    ShopListExportExcelView,
    ShopListExportPDFView,
    ShopListView,
    ShopTransactionExportExcelView,
    ShopTransactionExportPDFView,
    ShopUpdateView,
    UserLogoutView,
)

urlpatterns = [
    path('login/', LoginPageView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profil/', ProfileView.as_view(), name='profile'),

    path('', DashboardView.as_view(), name='dashboard'),

    path('mahsulotlar/', ProductListView.as_view(), name='product-list'),
    path('mahsulotlar/yangi/', ProductCreateView.as_view(), name='product-create'),
    path('mahsulotlar/<int:pk>/tahrirlash/', ProductUpdateView.as_view(), name='product-update'),
    path('mahsulotlar/<int:pk>/ochirish/', ProductDeleteView.as_view(), name='product-delete'),

    path('dokonlar/', ShopListView.as_view(), name='shop-list'),
    path('dokonlar/yangi/', ShopCreateView.as_view(), name='shop-create'),
    path('dokonlar/<int:pk>/', ShopDetailView.as_view(), name='shop-detail'),
    path('dokonlar/<int:pk>/tahrirlash/', ShopUpdateView.as_view(), name='shop-update'),
    path('dokonlar/<int:pk>/ochirish/', ShopDeleteView.as_view(), name='shop-delete'),
    path('dokonlar/<int:pk>/depozit/qoshish/', ShopDepositCreateView.as_view(), name='shop-deposit-create'),
    path('depozit/<int:pk>/tahrirlash/', ShopDepositUpdateView.as_view(), name='shop-deposit-update'),
    path('depozit/<int:pk>/ochirish/', ShopDepositDeleteView.as_view(), name='shop-deposit-delete'),
    path('dokonlar/<int:pk>/export/excel/', ShopTransactionExportExcelView.as_view(), name='shop-export-excel'),
    path('dokonlar/<int:pk>/export/pdf/', ShopTransactionExportPDFView.as_view(), name='shop-export-pdf'),
    path('dokonlar/export/excel/', ShopListExportExcelView.as_view(), name='shop-list-export-excel'),
    path('dokonlar/export/pdf/', ShopListExportPDFView.as_view(), name='shop-list-export-pdf'),

    path('buyurtmalar/', OrderListView.as_view(), name='order-list'),
    path('buyurtmalar/yangi/', OrderCreateView.as_view(), name='order-create'),
    path('buyurtmalar/<int:pk>/tahrirlash/', OrderUpdateView.as_view(), name='order-update'),
    path('buyurtmalar/<int:pk>/ochirish/', OrderDeleteView.as_view(), name='order-delete'),
    path('buyurtmalar/<int:pk>/json/', OrderDetailJsonView.as_view(), name='order-detail-json'),
    path('buyurtmalar/export/pdf/', OrderListExportPDFView.as_view(), name='order-list-export-pdf'),
    path('buyurtmalar/export/excel/', OrderListExportExcelView.as_view(), name='order-list-export-excel'),
    path('buyurtmalar/<int:pk>/export/pdf/', OrderExportPDFView.as_view(), name='order-export-pdf'),
    path('buyurtmalar/<int:pk>/export/excel/', OrderExportExcelView.as_view(), name='order-export-excel'),

    path('delivery/', DeliveryListView.as_view(), name='delivery-list'),
    path('delivery/<int:pk>/', DeliveryDetailView.as_view(), name='delivery-detail'),

    path('xodimlar/', EmployeeListView.as_view(), name='employee-list'),
    path('xodimlar/yangi/', EmployeeCreateView.as_view(), name='employee-create'),
    path('xodimlar/<int:pk>/', EmployeeDetailView.as_view(), name='employee-detail'),
    path('xodimlar/<int:pk>/tahrirlash/', EmployeeUpdateView.as_view(), name='employee-update'),
    path('xodimlar/export/pdf/', EmployeeListExportPDFView.as_view(), name='employee-list-export-pdf'),
    path('xodimlar/export/excel/', EmployeeListExportExcelView.as_view(), name='employee-list-export-excel'),
    path('xodimlar/<int:pk>/export/pdf/', EmployeeDetailExportPDFView.as_view(), name='employee-detail-export-pdf'),
    path('xodimlar/<int:pk>/export/excel/', EmployeeDetailExportExcelView.as_view(), name='employee-detail-export-excel'),
    path('xodimlar/faollik/', ActivityLogListView.as_view(), name='activity-log-list'),
    path('xodimlar/faollik/<int:pk>/json/', ActivityLogDetailJsonView.as_view(), name='activity-log-detail-json'),

    path('analitika/', AnalyticsView.as_view(), name='analytics'),
    path('analitika/data/', AnalyticsDataView.as_view(), name='analytics-data'),
    path('analitika/export/pdf/', AnalyticsExportPDFView.as_view(), name='analytics-export-pdf'),
    path('analitika/export/excel/', AnalyticsExportExcelView.as_view(), name='analytics-export-excel'),
]
